/** Reads `packages/tokens/dist/tokens.json` (generated by M2) for the docs pages and the registry. */
import {existsSync, readFileSync} from 'node:fs';
import {join} from 'node:path';
import {ROOT} from './paths.ts';

export type TokenStatus =
  'tecton-export' | 'tecton-binding' | 'upstream-default' | 'retained-default' | 'provisional';

export interface TokenMeta {
  name: string;
  category: string;
  light: string;
  dark: string;
  lightPath?: string;
  darkPath?: string;
  source: string;
  status: TokenStatus;
  description: string;
  provisional?: string;
}

export interface NonToken {
  name: string;
  reason: string;
}

export interface TokenData {
  counts: {tokens: number; palette: number; byStatus: Record<string, number>};
  breakpoints?: {status: string; note: string; values: Record<string, number>};
  provisionalNonTokens: NonToken[];
  retainedNonTokens: NonToken[];
  tectonDerivedNonTokens: NonToken[];
  tokens: TokenMeta[];
}

export const TOKENS_JSON = join(ROOT, 'packages/tokens/dist/tokens.json');

export function loadTokens(path: string = TOKENS_JSON): TokenData | undefined {
  if (!existsSync(path)) return undefined;
  const raw = JSON.parse(readFileSync(path, 'utf8')) as Omit<TokenData, 'tokens'> & {
    tokens: Record<string, TokenMeta>;
  };
  return {
    ...raw,
    provisionalNonTokens: raw.provisionalNonTokens ?? [],
    retainedNonTokens: raw.retainedNonTokens ?? [],
    tectonDerivedNonTokens: raw.tectonDerivedNonTokens ?? [],
    tokens: Object.values(raw.tokens).sort((a, b) =>
      a.name < b.name ? -1 : a.name > b.name ? 1 : 0,
    ),
  };
}
