/**
 * Internal report `reports/differences.md`: everything that differs from the upstream design system or is
 * not settled (recorded differences, waivers, provisional and retained values, requests, open owner
 * questions). It used to be a public docs page; the owner decided the upstream name must not appear on
 * the public site, so it is generated for the team only. Plain Markdown tables.
 */
import type {LoadedParity} from '../lib/parity.ts';
import type {TokenData, TokenMeta} from '../lib/tokens.ts';

/** A Markdown table with a bold caption line; cells are escaped for pipes and newlines. */
function table(
  caption: string,
  columns: {key: string; label: string; kind?: string}[],
  rows: Record<string, unknown>[],
  empty?: string,
): string {
  if (rows.length === 0) return `${caption}: ${empty ?? 'none'}.`;
  const cell = (value: unknown, kind?: string): string => {
    const raw = Array.isArray(value)
      ? value.join(', ')
      : typeof value === 'object' && value !== null
        ? String((value as {text?: string}).text ?? '')
        : typeof value === 'string'
          ? value
          : '';
    const text = raw.replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ');
    return kind === 'code' && text !== '' ? `\`${text}\`` : text;
  };
  return [
    `**${caption}**`,
    '',
    `| ${columns.map((column) => column.label).join(' | ')} |`,
    `| ${columns.map(() => '---').join(' | ')} |`,
    ...rows.map((row) => `| ${columns.map((column) => cell(row[column.key], column.kind)).join(' | ')} |`),
  ].join('\n');
}

// ------------------------------------------------------------------------------ differences

export interface OpenQuestion {
  id: string;
  question: string;
  context: string;
  resolved: boolean;
}

/** Reads the table in docs/plan/OPEN-QUESTIONS.md; ids the intro sentence calls resolved are marked. */
export function parseOpenQuestions(markdown: string): OpenQuestion[] {
  const resolvedRange = /Q-(\d+)\s*(?:…|\.\.\.|-|to)\s*Q-(\d+)\s+were resolved/i.exec(markdown);
  const from = resolvedRange ? Number(resolvedRange[1]) : Number.POSITIVE_INFINITY;
  const to = resolvedRange ? Number(resolvedRange[2]) : Number.NEGATIVE_INFINITY;
  const questions: OpenQuestion[] = [];
  for (const line of markdown.split('\n')) {
    const cells = /^\|\s*(Q-\d+)\s*\|(.*)\|\s*$/.exec(line);
    if (!cells) continue;
    const [question = '', context = ''] = cells[2]!.split(/\s\|\s/).map((cell) => cell.trim());
    const number = Number(cells[1]!.slice(2));
    questions.push({id: cells[1]!, question, context, resolved: number >= from && number <= to});
  }
  return questions;
}

export interface DifferencesInput {
  parity: readonly LoadedParity[];
  tokens: TokenData | undefined;
  openQuestions: readonly OpenQuestion[];
}

export function differencesReport(input: DifferencesInput): string {
  const {parity, tokens, openQuestions} = input;
  const out: string[] = [
    '# Differences and open items (internal report)',
    '',
    'GENERATED by tools/docs/generate.ts from every parity.json, packages/tokens/dist/tokens.json and docs/plan/OPEN-QUESTIONS.md. Internal: not part of the public docs site. Do not edit; do not commit.',
    '',
    'Everything this library does differently from upstream Astryx, or has not settled, in one place. Nothing here blocks use of an implemented component.',
    '',
  ];

  const entries = parity.flatMap(({data}) =>
    Object.entries(data.entries).map(([id, entry]) => ({folder: data.folder, id, entry})),
  );

  // 1. Recorded differences.
  const differences = entries.flatMap(({folder, id, entry}) =>
    (entry.differences ?? []).map((difference) => ({folder, id, difference, tag: entry.tag ?? ''})),
  );
  out.push(
    '## Recorded differences',
    '',
    'Approved API differences, accessibility improvements, Tecton visual choices and waivers, recorded per component in `parity.json`.',
    '',
    table(
      'Recorded differences',
      [
        {key: 'id', label: 'Id', kind: 'code'},
        {key: 'type', label: 'Type', kind: 'badge'},
        {key: 'component', label: 'Entry', kind: 'code'},
        {key: 'text', label: 'Difference'},
      ],
      differences.map(({id, difference}) => ({
        id: difference.id,
        type: difference.type,
        typeTone: difference.type === 'waiver' ? 'warning' : undefined,
        component: id,
        text: difference.text,
      })),
      'No differences are recorded yet.',
    ),
    '',
  );

  // 2. Waived API.
  const waived = entries.flatMap(({id, entry}) =>
    entry.api.filter((row) => row.as === 'waived').map((row) => ({id, row})),
  );
  out.push(
    '## Waived upstream API',
    '',
    table(
      'Waived upstream API',
      [
        {key: 'entry', label: 'Entry', kind: 'code'},
        {key: 'api', label: 'Astryx API', kind: 'code'},
        {key: 'kind', label: 'Kind'},
        {key: 'reason', label: 'Reason'},
      ],
      waived.map(({id, row}) => ({entry: id, api: row.upstream, kind: row.kind, reason: row.reason ?? ''})),
      'No upstream API is waived yet.',
    ),
    '',
  );

  // 3. Provisional values.
  const provisionalTokens = (tokens?.tokens ?? []).filter((token) => token.status === 'provisional');
  const provisionalColumns = [
    {key: 'name', label: 'Token', kind: 'code'},
    {key: 'category', label: 'Category'},
    {key: 'light', label: 'Light', kind: 'swatch'},
    {key: 'dark', label: 'Dark', kind: 'swatch'},
  ];
  out.push(
    '## Provisional values',
    '',
    `Tecton has no decision for these; they use the proposals in the semantic map (D-002) and are labelled provisional in the token metadata. ${provisionalTokens.length} tokens.`,
    '',
  );
  // The reason is shared by whole groups of tokens: state it once per group, not once per row.
  const byReason = new Map<string, TokenMeta[]>();
  for (const token of provisionalTokens) {
    const reason = token.provisional ?? token.description;
    byReason.set(reason, [...(byReason.get(reason) ?? []), token]);
  }
  let group = 0;
  for (const [reason, list] of byReason) {
    group++;
    out.push(
      `### Group ${group}: ${list[0]?.category ?? ''} (${list.length} tokens)`,
      '',
      reason,
      '',
      table(
        `Provisional tokens, group ${group}`,
        provisionalColumns,
        list.map((token) => ({name: token.name, category: token.category, light: token.light, dark: token.dark})),
      ),
      '',
    );
  }
  if (byReason.size === 0) out.push('No provisional tokens.', '');
  if ((tokens?.provisionalNonTokens.length ?? 0) > 0) {
    out.push(
      table(
        'Provisional values that are not tokens',
        [
          {key: 'name', label: 'Item', kind: 'code'},
          {key: 'reason', label: 'Reason'},
        ],
        tokens!.provisionalNonTokens.map((item) => ({name: item.name, reason: item.reason})),
      ),
      '',
    );
  }
  const componentProvisional = entries.filter(({entry}) => (entry.provisional?.length ?? 0) > 0);
  out.push(
    table(
      'Provisional values used by components',
      [
        {key: 'entry', label: 'Entry', kind: 'code'},
        {key: 'values', label: 'Provisional values', kind: 'codes'},
      ],
      componentProvisional.map(({id, entry}) => ({entry: id, values: entry.provisional ?? []})),
      'No component declares provisional values yet.',
    ),
    '',
  );

  // 4. Astryx-retained.
  const retained = (tokens?.tokens ?? []).filter((token) => token.status === 'astryx-retained');
  out.push(
    '## Astryx-retained values',
    '',
    'Motion, breakpoints and z-index are not brand tokens and Tecton has none, so they keep the Astryx values on purpose (D-013 Q-06).',
    '',
    table(
      'Astryx-retained tokens',
      [
        {key: 'name', label: 'Token', kind: 'code'},
        {key: 'category', label: 'Category'},
        {key: 'light', label: 'Value', kind: 'code'},
        {key: 'description', label: 'Description'},
      ],
      retained.map((token) => ({
        name: token.name,
        category: token.category,
        light: token.light,
        description: token.description,
      })),
      'No astryx-retained tokens.',
    ),
    '',
    table(
      'Astryx-retained values that are not tokens',
      [
        {key: 'name', label: 'Item', kind: 'code'},
        {key: 'reason', label: 'Reason'},
      ],
      (tokens?.astryxRetainedNonTokens ?? []).map((item) => ({name: item.name, reason: item.reason})),
      'None.',
    ),
    '',
  );
  if (tokens?.breakpoints) {
    out.push(
      table(
        'Breakpoints (astryx-retained)',
        [
          {key: 'name', label: 'Name', kind: 'code'},
          {key: 'width', label: 'Minimum width (px)', kind: 'code'},
        ],
        Object.entries(tokens.breakpoints.values).map(([name, width]) => ({name, width: String(width)})),
      ),
      '',
    );
  }

  // 5. Tecton-derived items.
  out.push(
    '## Tecton-derived values',
    '',
    'Values that follow the Tecton design system where it decides, even though upstream Astryx has a different default.',
    '',
    table(
      'Tecton-derived values that are not tokens',
      [
        {key: 'name', label: 'Item', kind: 'code'},
        {key: 'reason', label: 'Reason'},
      ],
      (tokens?.tectonDerivedNonTokens ?? []).map((item) => ({name: item.name, reason: item.reason})),
      'None.',
    ),
    '',
  );

  // 6. Requests.
  const tokenRequests = entries.flatMap(({id, entry}) =>
    (entry.tokenRequests ?? []).map((request) => ({id, request})),
  );
  const requests = entries.flatMap(({id, entry}) =>
    (entry.requests ?? []).map((request) => ({id, request})),
  );
  out.push(
    '## Requests to the orchestrator',
    '',
    table(
      'Token requests',
      [
        {key: 'entry', label: 'Entry', kind: 'code'},
        {key: 'name', label: 'Token', kind: 'code'},
        {key: 'reason', label: 'Reason'},
      ],
      tokenRequests.map(({id, request}) => ({entry: id, name: request.name, reason: request.reason})),
      'No token requests.',
    ),
    '',
    table(
      'Shared-file requests',
      [
        {key: 'entry', label: 'Entry', kind: 'code'},
        {key: 'file', label: 'File', kind: 'code'},
        {key: 'reason', label: 'Reason'},
      ],
      requests.map(({id, request}) => ({entry: id, file: request.file, reason: request.reason})),
      'No shared-file requests.',
    ),
    '',
  );

  // 7. Open questions.
  out.push(
    '## Open questions',
    '',
    'Owner decisions still needed, from `docs/plan/OPEN-QUESTIONS.md`. Resolved questions stay listed with their outcome recorded in the decision log (D-013).',
    '',
    table(
      'Open questions',
      [
        {key: 'id', label: 'Id', kind: 'code'},
        {key: 'state', label: 'State', kind: 'badge'},
        {key: 'question', label: 'Question'},
        {key: 'context', label: 'Context'},
      ],
      openQuestions.map((question) => ({
        id: question.id,
        state: question.resolved ? 'resolved (D-013)' : 'open',
        stateTone: question.resolved ? 'success' : 'warning',
        question: question.question,
        context: question.context,
      })),
      'No open questions.',
    ),
    '',
  );

  return out.join('\n');
}
