/**
 * Generated pages that are not one-per-component (A§16.4): the components overview, one overview per
 * category and the token reference. Each returns MDX source; tools/docs/generate.ts writes it under
 * `apps/docs/src/content/docs/` (gitignored).
 *
 * The public site never names the upstream design system and does not list what is not implemented:
 * "Parity status" and "Differences and open items" are internal reports (`reports/`, see
 * tools/docs/internal-reports.ts and tools/parity-report.ts).
 */
import {CATEGORIES, categorySlug, componentUrl} from '../lib/site.ts';
import {publicText, tokenStatusLabel} from '../lib/public-text.ts';
import type {TokenData, TokenMeta} from '../lib/tokens.ts';
import {escapeMdx, jsxValue, yamlString} from './mdx.ts';

const IMPORTS = `import DataTable from '@/components/DataTable.astro';`;

const banner = (source: string) =>
  `{/* GENERATED by tools/docs/generate.ts from ${source}. Do not edit; do not commit. */}`;

function frontmatter(
  title: string,
  description: string,
  sidebar?: {label?: string; order?: number},
): string {
  return [
    '---',
    `title: ${yamlString(title)}`,
    `description: ${yamlString(description)}`,
    ...(sidebar
      ? [
          'sidebar:',
          ...(sidebar.label ? [`  label: ${yamlString(sidebar.label)}`] : []),
          ...(sidebar.order === undefined ? [] : [`  order: ${sidebar.order}`]),
        ]
      : []),
    'editUrl: false',
    '---',
  ].join('\n');
}

function table(
  caption: string,
  columns: {key: string; label: string; kind?: string}[],
  rows: Record<string, unknown>[],
  empty?: string,
): string {
  return (
    `<DataTable caption=${JSON.stringify(caption)} columns=${jsxValue(columns)} rows=${jsxValue(rows)}` +
    `${empty ? ` empty=${JSON.stringify(empty)}` : ''} />`
  );
}

/** Documented component folders: folder -> facts shown on the overview pages. */
export type PageIndex = ReadonlyMap<
  string,
  {category: string; title: string; summary: string; tags: readonly string[]}
>;

const inCategory = (pages: PageIndex, category: string) =>
  [...pages].filter(([, page]) => page.category === category);

// ------------------------------------------------------------------------------ components

export function componentsOverviewPage(pages: PageIndex): string {
  return [
    frontmatter('Components', 'Every documented component, by category.', {
      label: 'Overview',
      order: 0,
    }),
    '',
    banner('the documented component folders'),
    '',
    IMPORTS,
    '',
    'Components are grouped in 11 categories. A category lists the components that are documented; more arrive as they are completed.',
    '',
    table(
      'Components by category',
      [
        {key: 'category', label: 'Category', kind: 'link'},
        {key: 'count', label: 'Documented components'},
      ],
      CATEGORIES.map((category) => ({
        category: {text: category, href: `/components/${categorySlug(category)}/`},
        count: String(inCategory(pages, category).length),
      })),
    ),
    '',
  ].join('\n');
}

export function categoryPage(category: string, pages: PageIndex): string {
  const rows = inCategory(pages, category);
  return [
    frontmatter(category, `${category} components.`, {label: 'Overview', order: 0}),
    '',
    banner('the documented component folders'),
    '',
    IMPORTS,
    '',
    rows.length === 0
      ? 'No components in this category are documented yet.'
      : `${rows.length} documented ${rows.length === 1 ? 'component' : 'components'}.`,
    '',
    ...(rows.length === 0
      ? []
      : [
          table(
            `${category} components`,
            [
              {key: 'name', label: 'Component', kind: 'link'},
              {key: 'tags', label: 'Elements', kind: 'codes'},
              {key: 'summary', label: 'Summary'},
            ],
            rows.map(([folder, page]) => ({
              name: {text: page.title, href: componentUrl(page.category, folder)},
              tags: page.tags.map((tag) => `<${tag}>`),
              summary: publicText(page.summary),
            })),
          ),
          '',
        ]),
  ].join('\n');
}

// ------------------------------------------------------------------------------------ tokens

const clip = (text: string, max = 150) =>
  text.length > max ? `${text.slice(0, max - 1).trimEnd()}…` : text;

const statusTone = (status: string): string | undefined =>
  status === 'provisional' ? 'warning' : status === 'retained-default' ? 'info' : undefined;

export function tokensPage(tokens: TokenData | undefined): string {
  const out: string[] = [
    frontmatter('Design tokens', 'Every design token with its light and dark values and its status.', {
      order: 3,
    }),
    '',
    banner('packages/tokens/dist/tokens.json'),
    '',
    IMPORTS,
    '',
  ];
  if (!tokens) {
    out.push('The token build has not run: run `pnpm generate`.', '');
    return out.join('\n');
  }
  out.push(
    `${tokens.counts.tokens} tokens over ${tokens.counts.palette} palette entries. Status: **Tecton** (from the Tecton design export, authoritative), **Tecton (bound)** (a Tecton role bound to a semantic token), **default** (a default value kept), **retained default** (kept on purpose, Tecton has no value) and **provisional** (proposed, not yet decided).`,
    '',
    table(
      'Tokens by status',
      [
        {key: 'status', label: 'Status', kind: 'badge'},
        {key: 'count', label: 'Tokens'},
      ],
      Object.entries(tokens.counts.byStatus).map(([status, count]) => ({
        status: tokenStatusLabel(status),
        statusTone: statusTone(status),
        count: String(count),
      })),
    ),
    '',
  );
  const byCategory = new Map<string, TokenMeta[]>();
  for (const token of tokens.tokens)
    byCategory.set(token.category, [...(byCategory.get(token.category) ?? []), token]);
  for (const [category, list] of [...byCategory].sort(([a], [b]) => (a < b ? -1 : 1))) {
    out.push(
      `## ${escapeMdx(category)}`,
      '',
      table(
        `${category} tokens`,
        [
          {key: 'name', label: 'Token', kind: 'code'},
          {key: 'light', label: 'Light', kind: 'swatch'},
          {key: 'dark', label: 'Dark', kind: 'swatch'},
          {key: 'status', label: 'Status', kind: 'badge'},
          {key: 'description', label: 'Description'},
        ],
        list.map((token) => ({
          name: token.name,
          light: token.light,
          dark: token.dark,
          status: tokenStatusLabel(token.status),
          statusTone: statusTone(token.status),
          description: clip(publicText(token.description)),
        })),
      ),
      '',
    );
  }
  return out.join('\n');
}
