/**
 * Generated pages that are not one-per-component (A§16.4): the components overview, one overview per
 * category, "Parity status", "Differences and open items" and the token reference. Each returns MDX
 * source; tools/docs/generate.ts writes it under `apps/docs/src/content/docs/` (gitignored).
 */
import type {LoadedParity} from '../lib/parity.ts';
import type {ParityReport, ParityRow} from '../lib/parity-report.ts';
import {CATEGORIES, categorySlug, componentUrl, REFERENCE_URLS} from '../lib/site.ts';
import type {TokenData, TokenMeta} from '../lib/tokens.ts';
import {escapeMdx, jsxValue, yamlString} from './mdx.ts';

const IMPORTS = `import DataTable from '@/components/DataTable.astro';`;

const banner = (source: string) =>
  `{/* GENERATED by tools/docs/generate.ts from ${source}. Do not edit; do not commit. */}`;

function frontmatter(title: string, description: string, sidebar?: {label?: string; order?: number}): string {
  return [
    '---',
    `title: ${yamlString(title)}`,
    `description: ${yamlString(description)}`,
    ...(sidebar
      ? [
          'sidebar:',
          ...(sidebar.label ? [`  label: ${yamlString(sidebar.label)}`] : []),
          ...(sidebar.order === undefined ? [] : [`  order: ${sidebar.order}`]),
        ]
      : []),
    'editUrl: false',
    '---',
  ].join('\n');
}

function table(
  caption: string,
  columns: {key: string; label: string; kind?: string}[],
  rows: Record<string, unknown>[],
  empty?: string,
): string {
  return (
    `<DataTable caption=${JSON.stringify(caption)} columns=${jsxValue(columns)} rows=${jsxValue(rows)}` +
    `${empty ? ` empty=${JSON.stringify(empty)}` : ''} />`
  );
}

const statusTone = (status: string): string | undefined =>
  status === 'verified' || status === 'implemented'
    ? 'success'
    : status === 'in-progress'
      ? 'warning'
      : undefined;

/** Component folders that have a generated page: folder -> category. */
export type PageIndex = ReadonlyMap<string, {category: string; title: string}>;

function rowLink(row: ParityRow, pages: PageIndex): {text: string; href: string} | string {
  const page = row.folder ? pages.get(row.folder) : undefined;
  return page && row.folder
    ? {text: row.name, href: componentUrl(page.category, row.folder)}
    : row.name;
}

// ------------------------------------------------------------------------------ components

export function componentsOverviewPage(report: ParityReport, pages: PageIndex): string {
  const core = report.entries.filter((row) => row.tier === 'core');
  const rows = CATEGORIES.map((category) => {
    const inCategory = core.filter((row) => row.category === category);
    const count = (status: string) => inCategory.filter((row) => row.status === status).length;
    return {
      category: {text: category, href: `/components/${categorySlug(category)}/`},
      total: String(inCategory.length),
      implemented: String(count('implemented') + count('verified')),
      inProgress: String(count('in-progress')),
      documented: String([...pages.values()].filter((page) => page.category === category).length),
    };
  });
  return [
    frontmatter('Components', 'Every public Astryx component, by category, with implementation status.', {
      label: 'Overview',
      order: 0,
    }),
    '',
    banner('the parity report'),
    '',
    IMPORTS,
    '',
    'Components are grouped in the 11 categories of the upstream Astryx documentation. A component page exists once its folder has documentation; the parity status page lists every entry, including those not started.',
    '',
    table(
      'Components by category',
      [
        {key: 'category', label: 'Category', kind: 'link'},
        {key: 'total', label: 'Upstream entries'},
        {key: 'implemented', label: 'Implemented'},
        {key: 'inProgress', label: 'In progress'},
        {key: 'documented', label: 'Documented pages'},
      ],
      rows,
    ),
    '',
    `See also [Parity status](${REFERENCE_URLS.parity}) and [Differences and open items](${REFERENCE_URLS.differences}).`,
    '',
  ].join('\n');
}

export function categoryPage(category: string, report: ParityReport, pages: PageIndex): string {
  const rows = report.entries.filter((row) => row.tier === 'core' && row.category === category);
  const documented = [...pages.values()].filter((page) => page.category === category).length;
  return [
    frontmatter(category, `Astryx ${category} components and their implementation status.`, {
      label: 'Overview',
      order: 0,
    }),
    '',
    banner('the parity report'),
    '',
    IMPORTS,
    '',
    `${rows.length} upstream ${category} entries; ${documented} documented so far.`,
    '',
    table(
      `${category} components`,
      [
        {key: 'name', label: 'Component', kind: 'link'},
        {key: 'kind', label: 'Kind'},
        {key: 'tag', label: 'Element', kind: 'code'},
        {key: 'status', label: 'Status', kind: 'badge'},
        {key: 'api', label: 'API mapped'},
      ],
      rows.map((row) => ({
        name: rowLink(row, pages),
        kind: row.kind,
        tag: row.tag ? `<${row.tag}>` : '',
        status: row.status,
        statusTone: statusTone(row.status),
        api: row.api.expected === 0 ? '' : `${row.api.mapped}/${row.api.expected}`,
      })),
      'No upstream entries in this category.',
    ),
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------------- parity

export function parityStatusPage(report: ParityReport, pages: PageIndex): string {
  const summaryRows = (['core', 'extension'] as const).map((tier) => ({
    tier,
    total: String(report.summary[tier].total),
    notStarted: String(report.summary[tier]['not-started']),
    inProgress: String(report.summary[tier]['in-progress']),
    implemented: String(report.summary[tier].implemented),
    verified: String(report.summary[tier].verified),
  }));

  const columns = [
    {key: 'name', label: 'Entry', kind: 'link'},
    {key: 'kind', label: 'Kind'},
    {key: 'tag', label: 'Element', kind: 'code'},
    {key: 'status', label: 'Status', kind: 'badge'},
    {key: 'api', label: 'API mapped'},
    {key: 'waived', label: 'Waived'},
    {key: 'docs', label: 'Docs sections'},
    {key: 'tests', label: 'Test categories'},
    {key: 'keyboard', label: 'Keyboard rows'},
    {key: 'provisional', label: 'Provisional'},
  ];
  const toRow = (row: ParityRow) => ({
    name: rowLink(row, pages),
    kind: row.kind,
    tag: row.tag ? `<${row.tag}>` : '',
    status: row.status,
    statusTone: statusTone(row.status),
    api: row.api.expected === 0 ? '' : `${row.api.mapped}/${row.api.expected}`,
    waived: row.api.waived === 0 ? '' : String(row.api.waived),
    docs: row.docs.page ? `${row.docs.sectionsPresent}/${row.docs.sectionsRequired}` : '',
    tests: row.behaviour.testCategories.join(', '),
    keyboard: row.keyboardRows === 0 ? '' : String(row.keyboardRows),
    provisional: row.theming.provisional.length === 0 ? '' : String(row.theming.provisional.length),
  });

  const sections: string[] = [];
  for (const category of CATEGORIES) {
    const rows = report.entries.filter((row) => row.tier === 'core' && row.category === category);
    if (rows.length === 0) continue;
    sections.push(`## ${category}`, '', table(`${category}: parity status`, columns, rows.map(toRow)), '');
  }
  const uncategorised = report.entries.filter((row) => row.tier === 'core' && !CATEGORIES.includes(row.category as never));
  if (uncategorised.length > 0) {
    sections.push('## Providers and other entries', '', table('Providers and other entries', columns, uncategorised.map(toRow)), '');
  }
  const extension = report.entries.filter((row) => row.tier === 'extension');
  sections.push(
    '## Extension packages',
    '',
    'Lab, charts, richtext and vega entries are tracked as experimental and scheduled after the core release (D-006).',
    '',
    table('Extension packages: parity status', columns, extension.map(toRow)),
    '',
  );

  return [
    frontmatter('Parity status', 'Implementation status of every upstream Astryx component and extension entry.', {
      order: 1,
    }),
    '',
    banner('reports/parity.json'),
    '',
    IMPORTS,
    '',
    `Upstream Astryx at \`${report.generatedFrom.manifestCommit.slice(0, 7)}\`. One row per upstream entry: status, how much of its API is mapped or waived, how many of the ${report.entries[0]?.docs.sectionsRequired ?? 10} required documentation sections exist, and which test categories the folder records. Waived rows are disclosed gaps, not silent ones.`,
    '',
    table(
      'Parity summary',
      [
        {key: 'tier', label: 'Tier'},
        {key: 'total', label: 'Total'},
        {key: 'notStarted', label: 'Not started'},
        {key: 'inProgress', label: 'In progress'},
        {key: 'implemented', label: 'Implemented'},
        {key: 'verified', label: 'Verified'},
      ],
      summaryRows,
    ),
    '',
    ...(report.problems.length > 0
      ? [
          '## Problems found by parity:check',
          '',
          table(
            'Parity problems',
            [
              {key: 'file', label: 'File', kind: 'code'},
              {key: 'message', label: 'Problem'},
            ],
            report.problems.map((problem) => ({file: problem.file, message: problem.message})),
          ),
          '',
        ]
      : []),
    ...sections,
  ].join('\n');
}

// ------------------------------------------------------------------------------ differences

export interface OpenQuestion {
  id: string;
  question: string;
  context: string;
  resolved: boolean;
}

/** Reads the table in docs/plan/OPEN-QUESTIONS.md; ids the intro sentence calls resolved are marked. */
export function parseOpenQuestions(markdown: string): OpenQuestion[] {
  const resolvedRange = /Q-(\d+)\s*(?:…|\.\.\.|-|to)\s*Q-(\d+)\s+were resolved/i.exec(markdown);
  const from = resolvedRange ? Number(resolvedRange[1]) : Number.POSITIVE_INFINITY;
  const to = resolvedRange ? Number(resolvedRange[2]) : Number.NEGATIVE_INFINITY;
  const questions: OpenQuestion[] = [];
  for (const line of markdown.split('\n')) {
    const cells = /^\|\s*(Q-\d+)\s*\|(.*)\|\s*$/.exec(line);
    if (!cells) continue;
    const [question = '', context = ''] = cells[2]!.split(/\s\|\s/).map((cell) => cell.trim());
    const number = Number(cells[1]!.slice(2));
    questions.push({id: cells[1]!, question, context, resolved: number >= from && number <= to});
  }
  return questions;
}

export interface DifferencesInput {
  parity: readonly LoadedParity[];
  tokens: TokenData | undefined;
  openQuestions: readonly OpenQuestion[];
}

export function differencesPage(input: DifferencesInput): string {
  const {parity, tokens, openQuestions} = input;
  const out: string[] = [
    frontmatter(
      'Differences and open items',
      'Approved differences from Astryx, provisional and astryx-retained values, requests and open owner questions.',
      {order: 2},
    ),
    '',
    banner('every parity.json, packages/tokens/dist/tokens.json and docs/plan/OPEN-QUESTIONS.md'),
    '',
    IMPORTS,
    '',
    'Everything this library does differently from upstream Astryx, or has not settled, in one place. Nothing here blocks use of an implemented component.',
    '',
  ];

  const entries = parity.flatMap(({data}) =>
    Object.entries(data.entries).map(([id, entry]) => ({folder: data.folder, id, entry})),
  );

  // 1. Recorded differences.
  const differences = entries.flatMap(({folder, id, entry}) =>
    (entry.differences ?? []).map((difference) => ({folder, id, difference, tag: entry.tag ?? ''})),
  );
  out.push(
    '## Recorded differences',
    '',
    'Approved API differences, accessibility improvements, Tecton visual choices and waivers, recorded per component in `parity.json`.',
    '',
    table(
      'Recorded differences',
      [
        {key: 'id', label: 'Id', kind: 'code'},
        {key: 'type', label: 'Type', kind: 'badge'},
        {key: 'component', label: 'Entry', kind: 'code'},
        {key: 'text', label: 'Difference'},
      ],
      differences.map(({id, difference}) => ({
        id: difference.id,
        type: difference.type,
        typeTone: difference.type === 'waiver' ? 'warning' : undefined,
        component: id,
        text: difference.text,
      })),
      'No differences are recorded yet.',
    ),
    '',
  );

  // 2. Waived API.
  const waived = entries.flatMap(({id, entry}) =>
    entry.api.filter((row) => row.as === 'waived').map((row) => ({id, row})),
  );
  out.push(
    '## Waived upstream API',
    '',
    table(
      'Waived upstream API',
      [
        {key: 'entry', label: 'Entry', kind: 'code'},
        {key: 'api', label: 'Astryx API', kind: 'code'},
        {key: 'kind', label: 'Kind'},
        {key: 'reason', label: 'Reason'},
      ],
      waived.map(({id, row}) => ({entry: id, api: row.upstream, kind: row.kind, reason: row.reason ?? ''})),
      'No upstream API is waived yet.',
    ),
    '',
  );

  // 3. Provisional values.
  const provisionalTokens = (tokens?.tokens ?? []).filter((token) => token.status === 'provisional');
  const provisionalColumns = [
    {key: 'name', label: 'Token', kind: 'code'},
    {key: 'category', label: 'Category'},
    {key: 'light', label: 'Light', kind: 'swatch'},
    {key: 'dark', label: 'Dark', kind: 'swatch'},
    {key: 'reason', label: 'Why provisional'},
  ];
  out.push(
    '## Provisional values',
    '',
    `Tecton has no decision for these; they use the proposals in the semantic map (D-002) and are labelled provisional in the token metadata. ${provisionalTokens.length} tokens.`,
    '',
    table(
      'Provisional tokens',
      provisionalColumns,
      provisionalTokens.map((token) => ({
        name: token.name,
        category: token.category,
        light: token.light,
        dark: token.dark,
        reason: token.provisional ?? token.description,
      })),
      'No provisional tokens.',
    ),
    '',
  );
  if ((tokens?.provisionalNonTokens.length ?? 0) > 0) {
    out.push(
      table(
        'Provisional values that are not tokens',
        [
          {key: 'name', label: 'Item', kind: 'code'},
          {key: 'reason', label: 'Reason'},
        ],
        tokens!.provisionalNonTokens.map((item) => ({name: item.name, reason: item.reason})),
      ),
      '',
    );
  }
  const componentProvisional = entries.filter(({entry}) => (entry.provisional?.length ?? 0) > 0);
  out.push(
    table(
      'Provisional values used by components',
      [
        {key: 'entry', label: 'Entry', kind: 'code'},
        {key: 'values', label: 'Provisional values', kind: 'codes'},
      ],
      componentProvisional.map(({id, entry}) => ({entry: id, values: entry.provisional ?? []})),
      'No component declares provisional values yet.',
    ),
    '',
  );

  // 4. Astryx-retained.
  const retained = (tokens?.tokens ?? []).filter((token) => token.status === 'astryx-retained');
  out.push(
    '## Astryx-retained values',
    '',
    'Motion, breakpoints and z-index are not brand tokens and Tecton has none, so they keep the Astryx values on purpose (D-013 Q-06).',
    '',
    table(
      'Astryx-retained tokens',
      [
        {key: 'name', label: 'Token', kind: 'code'},
        {key: 'category', label: 'Category'},
        {key: 'light', label: 'Value', kind: 'code'},
        {key: 'description', label: 'Description'},
      ],
      retained.map((token) => ({
        name: token.name,
        category: token.category,
        light: token.light,
        description: token.description,
      })),
      'No astryx-retained tokens.',
    ),
    '',
    table(
      'Astryx-retained values that are not tokens',
      [
        {key: 'name', label: 'Item', kind: 'code'},
        {key: 'reason', label: 'Reason'},
      ],
      (tokens?.astryxRetainedNonTokens ?? []).map((item) => ({name: item.name, reason: item.reason})),
      'None.',
    ),
    '',
  );
  if (tokens?.breakpoints) {
    out.push(
      table(
        'Breakpoints (astryx-retained)',
        [
          {key: 'name', label: 'Name', kind: 'code'},
          {key: 'width', label: 'Minimum width (px)', kind: 'code'},
        ],
        Object.entries(tokens.breakpoints.values).map(([name, width]) => ({name, width: String(width)})),
      ),
      '',
    );
  }

  // 5. Tecton-derived items.
  out.push(
    '## Tecton-derived values',
    '',
    'Values that follow the Tecton design system where it decides, even though upstream Astryx has a different default.',
    '',
    table(
      'Tecton-derived values that are not tokens',
      [
        {key: 'name', label: 'Item', kind: 'code'},
        {key: 'reason', label: 'Reason'},
      ],
      (tokens?.tectonDerivedNonTokens ?? []).map((item) => ({name: item.name, reason: item.reason})),
      'None.',
    ),
    '',
  );

  // 6. Requests.
  const tokenRequests = entries.flatMap(({id, entry}) =>
    (entry.tokenRequests ?? []).map((request) => ({id, request})),
  );
  const requests = entries.flatMap(({id, entry}) =>
    (entry.requests ?? []).map((request) => ({id, request})),
  );
  out.push(
    '## Requests to the orchestrator',
    '',
    table(
      'Token requests',
      [
        {key: 'entry', label: 'Entry', kind: 'code'},
        {key: 'name', label: 'Token', kind: 'code'},
        {key: 'reason', label: 'Reason'},
      ],
      tokenRequests.map(({id, request}) => ({entry: id, name: request.name, reason: request.reason})),
      'No token requests.',
    ),
    '',
    table(
      'Shared-file requests',
      [
        {key: 'entry', label: 'Entry', kind: 'code'},
        {key: 'file', label: 'File', kind: 'code'},
        {key: 'reason', label: 'Reason'},
      ],
      requests.map(({id, request}) => ({entry: id, file: request.file, reason: request.reason})),
      'No shared-file requests.',
    ),
    '',
  );

  // 7. Open questions.
  out.push(
    '## Open questions',
    '',
    'Owner decisions still needed, from `docs/plan/OPEN-QUESTIONS.md`. Resolved questions stay listed with their outcome recorded in the decision log (D-013).',
    '',
    table(
      'Open questions',
      [
        {key: 'id', label: 'Id', kind: 'code'},
        {key: 'state', label: 'State', kind: 'badge'},
        {key: 'question', label: 'Question'},
        {key: 'context', label: 'Context'},
      ],
      openQuestions.map((question) => ({
        id: question.id,
        state: question.resolved ? 'resolved (D-013)' : 'open',
        stateTone: question.resolved ? 'success' : 'warning',
        question: question.question,
        context: question.context,
      })),
      'No open questions.',
    ),
    '',
  );

  return out.join('\n');
}

// ------------------------------------------------------------------------------------ tokens

const clip = (text: string, max = 150) => (text.length > max ? `${text.slice(0, max - 1).trimEnd()}…` : text);

export function tokensPage(tokens: TokenData | undefined): string {
  const out: string[] = [
    frontmatter('Design tokens', 'Every design token with its light and dark values and its status.', {order: 3}),
    '',
    banner('packages/tokens/dist/tokens.json'),
    '',
    IMPORTS,
    '',
  ];
  if (!tokens) {
    out.push('The token build has not run: run `pnpm generate`.', '');
    return out.join('\n');
  }
  out.push(
    `${tokens.counts.tokens} tokens over ${tokens.counts.palette} palette entries. Status: **tecton-export** (the Tecton design export, authoritative, D-001), **tecton-astryx** (the owner's Astryx theme binding), **upstream-default** (an Astryx default kept), **astryx-retained** (kept on purpose, no Tecton value) and **provisional** (proposed, see [Differences and open items](${REFERENCE_URLS.differences})).`,
    '',
    table(
      'Tokens by status',
      [
        {key: 'status', label: 'Status', kind: 'badge'},
        {key: 'count', label: 'Tokens'},
      ],
      Object.entries(tokens.counts.byStatus).map(([status, count]) => ({
        status,
        statusTone: status === 'provisional' ? 'warning' : status === 'astryx-retained' ? 'info' : undefined,
        count: String(count),
      })),
    ),
    '',
  );
  const byCategory = new Map<string, TokenMeta[]>();
  for (const token of tokens.tokens) byCategory.set(token.category, [...(byCategory.get(token.category) ?? []), token]);
  for (const [category, list] of [...byCategory].sort(([a], [b]) => (a < b ? -1 : 1))) {
    out.push(
      `## ${escapeMdx(category)}`,
      '',
      table(
        `${category} tokens`,
        [
          {key: 'name', label: 'Token', kind: 'code'},
          {key: 'light', label: 'Light', kind: 'swatch'},
          {key: 'dark', label: 'Dark', kind: 'swatch'},
          {key: 'status', label: 'Status', kind: 'badge'},
          {key: 'description', label: 'Description'},
        ],
        list.map((token) => ({
          name: token.name,
          light: token.light,
          dark: token.dark,
          status: token.status,
          statusTone: token.status === 'provisional' ? 'warning' : token.status === 'astryx-retained' ? 'info' : undefined,
          description: clip(token.description),
        })),
      ),
      '',
    );
  }
  return out.join('\n');
}
