/**
 * Tecton domain icon extraction (A§12, D-013 Q-02): reads the authored glyph data
 * `packages/icons/src/tecton/glyphs/<name>.ts` (the owner's set, provenance in
 * `packages/icons/src/tecton/README.md`) and writes
 *
 *   packages/icons/src/tecton/<name>.ts   `IconDefinition` module: `outlined`, `filled`, default = outlined
 *   packages/icons/src/tecton.ts          `tectonIcons` lazy loaders (`<name>`, `<name>-filled`) + metadata
 *
 * Both are generated, gitignored build output (`pnpm generate`). The conversion itself is
 * `tools/icons/tecton-convert.ts` (exact paths where possible, a sanitisable raw-SVG body otherwise).
 */
import {existsSync, mkdirSync, readdirSync, readFileSync, rmSync} from 'node:fs';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {writeIfChanged} from '../lib/fs.ts';
import {ROOT, rel} from '../lib/paths.ts';
import {convertGlyph, type GlyphDefinition} from './tecton-convert.ts';

const TECTON_DIR = join(ROOT, 'packages', 'icons', 'src', 'tecton');
const GLYPHS_DIR = join(TECTON_DIR, 'glyphs');
const REGISTRY_FILE = join(ROOT, 'packages', 'icons', 'src', 'tecton.ts');

/** The shape of a glyph data file (`glyphs/types.ts`). */
export interface TectonIconData {
  name: string;
  label: string;
  description: string;
  viewBox: string;
  colored?: boolean;
  outlined: string;
  filled: string;
}

export const GENERATED_HEADER = (commit: string) =>
  `// GENERATED by tools/icons/extract-tecton.ts from packages/icons/src/tecton/glyphs (the owner's Tecton domain icon set, D-013 Q-02; source commit ${commit}). Do not edit.`;

/** JSON with single quotes for the value strings the repository style expects; keys stay unquoted. */
const literal = (value: unknown) => JSON.stringify(value);

function renderDefinition(definition: GlyphDefinition, viewBox: string): string {
  const paths = definition.paths
    .map((path) =>
      path.fillRule
        ? `{d: ${literal(path.d)}, fillRule: '${path.fillRule}'}`
        : `{d: ${literal(path.d)}}`,
    )
    .join(', ');
  const fields = [`viewBox: ${literal(viewBox)}`, `paths: [${paths}]`, `mode: 'fill'`];
  if (definition.svg !== undefined) fields.push(`svg: ${literal(definition.svg)}`);
  if (definition.colored) fields.push('colored: true');
  return `{${fields.join(', ')}}`;
}

export function renderIconModule(
  icon: TectonIconData,
  outlined: GlyphDefinition,
  filled: GlyphDefinition,
  commit: string,
): string {
  const same = JSON.stringify(outlined) === JSON.stringify(filled);
  return `${GENERATED_HEADER(commit)}
import type {IconDefinition} from '../types.js';

/** ${icon.label}, outlined: ${icon.description}. */
export const outlined: IconDefinition = ${renderDefinition(outlined, icon.viewBox)};

/** ${icon.label}, filled${same ? ' (the source draws the same glyph for both variants)' : ''}. */
export const filled: IconDefinition = ${same ? 'outlined' : renderDefinition(filled, icon.viewBox)};

export default outlined;
`;
}

export function renderRegistry(icons: readonly TectonIconData[], commit: string): string {
  const loaders = icons.flatMap((icon) => [
    `  ${literal(icon.name)}: () => import('./tecton/${icon.name}.js').then((module) => module.outlined),`,
    `  ${literal(`${icon.name}-filled`)}: () => import('./tecton/${icon.name}.js').then((module) => module.filled),`,
  ]);
  const meta = icons.map(
    (icon) =>
      `  ${literal(icon.name)}: {label: ${literal(icon.label)}, description: ${literal(icon.description)}, colored: ${icon.colored === true}},`,
  );
  return `${GENERATED_HEADER(commit)}
import type {IconLoader} from './types.js';

/**
 * The Tecton domain icon set (D-013 Q-02): 18 oil & gas / subsurface glyphs, each as a lazy loader under its
 * kebab name (outlined) and \`<name>-filled\`. The default icon set registers these (\`default.js\`), so
 * \`<tct-icon name="well">\` and \`name="well-filled"\` work without any registration; register them yourself
 * only to rename them or to add a namespace:
 *
 *   registerIcons(tectonIcons, {namespace: 'tecton'});   // <tct-icon name="tecton:well">
 *
 * Per-icon modules (\`@tecton-astryx/icons/tecton/<name>.js\`) export \`outlined\`, \`filled\` and a default
 * (outlined) for tree-shakeable direct imports.
 */
export const tectonIcons = {
${loaders.join('\n')}
} as const satisfies Record<string, IconLoader>;

/** Every registered Tecton name: \`<name>\` (outlined) and \`<name>-filled\`. */
export type TectonIconName = keyof typeof tectonIcons;

/** Glyph names (outlined; add \`-filled\` for the filled variant), alphabetical. */
export const tectonIconNames: readonly string[] = ${literal(icons.map((icon) => icon.name))};

/** Human-readable metadata for galleries and search. \`colored\`: the glyph carries colours of its own. */
export const tectonIconMeta: Readonly<
  Record<string, {label: string; description: string; colored: boolean}>
> = {
${meta.join('\n')}
};
`;
}

async function main(): Promise<number> {
  if (!existsSync(GLYPHS_DIR)) {
    console.error(`  icons: ${rel(GLYPHS_DIR)} not found`);
    return 1;
  }
  const commit = readFileSync(join(GLYPHS_DIR, 'SOURCE-COMMIT'), 'utf8').trim();
  const files = readdirSync(GLYPHS_DIR)
    .filter((file) => file.endsWith('.ts') && file !== 'types.ts')
    .sort();

  const icons: TectonIconData[] = [];
  for (const file of files) {
    const module = (await import(pathToFileURL(join(GLYPHS_DIR, file)).href)) as Record<
      string,
      unknown
    >;
    const icon = Object.values(module).find(
      (value): value is TectonIconData =>
        typeof value === 'object' && value !== null && 'outlined' in value,
    );
    if (!icon || `${icon.name}.ts` !== file) {
      console.error(`  icons: ${file}: no glyph data whose name matches the file name`);
      return 1;
    }
    icons.push(icon);
  }
  // Gallery order: by glyph name (file names sort differently: `well-pick.ts` < `well.ts`).
  icons.sort((left, right) => (left.name < right.name ? -1 : left.name > right.name ? 1 : 0));

  mkdirSync(TECTON_DIR, {recursive: true});
  const wanted = new Set(icons.map((icon) => `${icon.name}.ts`));
  for (const file of readdirSync(TECTON_DIR))
    if (file.endsWith('.ts') && !wanted.has(file)) rmSync(join(TECTON_DIR, file));

  let changed = 0;
  let raw = 0;
  for (const icon of icons) {
    let source: string;
    try {
      const outlined = convertGlyph(icon.outlined, icon.viewBox);
      const filled = convertGlyph(icon.filled, icon.viewBox);
      for (const variant of [outlined, filled]) {
        if ((variant.svg !== undefined) !== (icon.colored === true))
          throw new Error(
            `data says colored=${icon.colored === true} but the conversion ${variant.svg !== undefined ? 'needs' : 'does not need'} a raw SVG body`,
          );
      }
      if (outlined.svg !== undefined) raw++;
      source = renderIconModule(icon, outlined, filled, commit);
    } catch (error) {
      console.error(`  icons: ${icon.name}: ${(error as Error).message}`);
      return 1;
    }
    if (writeIfChanged(join(TECTON_DIR, `${icon.name}.ts`), source)) changed++;
  }
  const registryChanged = writeIfChanged(REGISTRY_FILE, renderRegistry(icons, commit));

  console.log(
    `  icons: tecton: ${icons.length} glyph modules (${changed} changed, ${raw} with a raw SVG body)` +
      `${registryChanged ? ', wrote tecton.ts' : ''}`,
  );
  return 0;
}

// Only run as a script (the tests import the render functions).
if (import.meta.filename === process.argv[1]) process.exit(await main());
