/**
 * `tokens.css` and `palette.css` (A§5.4, styling.md §4).
 *
 * Guides consulted: [mwg:dark-mode] (color-scheme on :root, light-dark() tokens with a
 * prefers-color-scheme fallback, accent-color, no forced root scheme), [mwg:component-specific-light-dark-theme]
 * (an element that switches scheme also sets a background, `color` and `accent-color`; tokens are never
 * registered as `<color>` so light-dark() stays live for descendants), [mwg:css] (cascade layers declared
 * up front, `:where()` for zero specificity, forced-colors system colours).
 */
import type {Palette} from './palette.ts';
import type {Mode, SemanticMap, Token} from './model.ts';
import {cssLightDark, cssValue, dependsOn, isModeInvariant, pathOf} from './resolve.ts';

/** Declared first in every stylesheet so load order never changes layer order (A§5.4). */
export const LAYER_STATEMENT = '@layer tecton.reset, tecton.tokens, tecton.light-dom;';
const SUPPORTS_LIGHT_DARK = '@supports (color: light-dark(red, red))';

export const GENERATED_BANNER = (file: string, what: string) => `/*!
 * @tecton-astryx/tokens: ${file}
 * ${what}
 * GENERATED by packages/tokens/scripts/generate.ts from packages/tokens/src/inputs/. Do not edit.
 */`;

/** Tokens that get a system colour under forced-colors (styling.md §9.1, [mwg:css] Forced Colors Mode). */
const FORCED_COLORS: Record<string, string> = {
  '--color-background-body': 'Canvas',
  '--color-background-surface': 'Canvas',
  '--color-background-card': 'Canvas',
  '--color-background-popover': 'Canvas',
  '--color-text-primary': 'CanvasText',
  '--color-text-secondary': 'CanvasText',
  '--color-text-disabled': 'GrayText',
  '--color-text-accent': 'LinkText',
  '--color-icon-primary': 'CanvasText',
  '--color-icon-secondary': 'CanvasText',
  '--color-icon-disabled': 'GrayText',
  '--color-icon-accent': 'LinkText',
  '--color-border': 'ButtonBorder',
  '--color-border-emphasized': 'ButtonBorder',
  '--color-accent': 'Highlight',
  '--color-on-accent': 'HighlightText',
  '--focus-outline-color': 'Highlight',
};

/** Tokens re-pinned inside `[data-media-theme]` (onMediaTokens.ts + the Tecton pins). */
const MEDIA_PINNED = [
  '--color-text-primary',
  '--color-text-secondary',
  '--color-background-surface',
  '--color-border',
] as const;

interface Sections {
  /** Everything after the layer statement, for concatenation into tecton.css. */
  body: string;
}

const indent = (text: string, spaces: number) =>
  text
    .split('\n')
    .map((line) => (line === '' ? line : ' '.repeat(spaces) + line))
    .join('\n');

function declarationComment(token: Token): string {
  const parts: string[] = [];
  const value = token.value;
  if (value.kind === 'color' || value.kind === 'shadow') {
    const light = pathOf(token, 'light');
    const dark = pathOf(token, 'dark');
    if (light !== undefined || dark !== undefined)
      parts.push(light === dark ? (light ?? '') : `${light ?? '-'} | ${dark ?? '-'}`);
  } else if (value.kind === 'ref') {
    parts.push(`-> ${value.name}`);
  }
  if (token.override) parts.push('override');
  if (token.provisional !== undefined) parts.push('provisional');
  if (token.retained !== undefined) parts.push('astryx-retained');
  return parts.length === 0 ? '' : ` /* ${parts.join(' ')} */`;
}

function declarations(
  tokens: readonly Token[],
  render: (token: Token) => string | undefined,
  withComments: boolean,
): string {
  const lines: string[] = [];
  let category: string | undefined;
  for (const token of tokens) {
    const value = render(token);
    if (value === undefined) continue;
    if (withComments && token.category !== category) {
      category = token.category;
      lines.push(`/* ${category} */`);
    }
    lines.push(`${token.name}: ${value};${withComments ? declarationComment(token) : ''}`);
  }
  return lines.join('\n');
}

export function emitTokensCss(
  tokens: readonly Token[],
  byName: ReadonlyMap<string, Token>,
  map: SemanticMap,
): Sections & {css: string} {
  const light = declarations(tokens, (t) => cssValue(t, 'light', byName, false), true);
  const varying = tokens.filter((token) => !isModeInvariant(token, byName));
  const dark = declarations(varying, (t) => cssValue(t, 'dark', byName, false), false);
  const lightOnly = declarations(varying, (t) => cssValue(t, 'light', byName, false), false);
  // References keep their base declaration: on the modern path the substituted stream inherits intact.
  const lightDark = declarations(
    varying.filter((token) => token.value.kind !== 'ref'),
    (t) => cssLightDark(t, byName),
    false,
  );
  // References that read a pinned token must be substituted again inside a media theme.
  const pinnedNames = new Set<string>([...MEDIA_PINNED, '--color-icon-primary', '--color-accent']);
  const mediaDependents = tokens
    .filter((token) => dependsOn(token, pinnedNames, byName))
    .map((token) => `${token.name}: ${cssValue(token, 'light', byName, false)};`);

  const schemeBlock = (mode: Mode) =>
    [
      `color-scheme: ${mode};`,
      'background-color: var(--color-background-body);',
      'color: var(--color-text-primary);',
      'accent-color: var(--color-accent);',
    ].join('\n');

  const mediaBlock = (mode: 'dark' | 'light') => {
    const side = mode; // onDark pins the dark side of each pair, onLight the light side
    const pinned = MEDIA_PINNED.map((name) => {
      const token = byName.get(name);
      if (!token) throw new Error(`media theme pins unknown token ${name}`);
      // The map's onMedia values document the intent; the resolved token value (export first) wins.
      const mapped = map.onMedia[mode === 'dark' ? 'onDark' : 'onLight'].tecton[name];
      if (!mapped) throw new Error(`semantic map: onMedia ${mode} does not pin ${name}`);
      return `${name}: ${cssValue(token, side, byName, false)};`;
    });
    return [
      `color-scheme: ${mode};`,
      ...pinned,
      ...mediaDependents,
      `--color-icon-primary: var(--color-on-${mode});`,
      `--color-accent: var(--color-on-${mode});`,
      'color: var(--color-text-primary);',
      'accent-color: var(--color-accent);',
    ].join('\n');
  };

  const forced = Object.entries(FORCED_COLORS)
    .map(([name, value]) => {
      if (!byName.has(name)) throw new Error(`forced-colors block names unknown token ${name}`);
      return `${name}: ${value};`;
    })
    .join('\n');

  const body = `@layer tecton.tokens {
  /* Baseline and fallback: light values. Every token is declared here, once. */
  :where(:root) {
    color-scheme: light dark;
    accent-color: var(--color-accent);
${indent(light, 4)}
  }

  /* Tier 2 fallback for engines without light-dark() (Chrome < 123, Safari < 17.5): dark values,
     the system preference first, then explicit [data-theme] islands. */
  @supports not (color: light-dark(red, red)) {
    @media (prefers-color-scheme: dark) {
      :where(:root:not([data-theme="light"])) {
${indent(dark, 8)}
      }
    }
    :where([data-theme="dark"]) {
${indent(dark, 6)}
    }
    :where([data-theme="light"]) {
${indent(lightOnly, 6)}
    }
  }

  /* An element that switches scheme also sets its background, color and accent-color: inherited
     <color> values arrive already resolved. [mwg:component-specific-light-dark-theme] */
  :where([data-theme="dark"]) {
${indent(schemeBlock('dark'), 4)}
  }
  :where([data-theme="light"]) {
${indent(schemeBlock('light'), 4)}
  }

  /* Modern path: one light-dark() value per varying token. Declared after the fallbacks so it wins on
     the root; tokens stay unregistered so descendants re-resolve under their own color-scheme. */
  ${SUPPORTS_LIGHT_DARK} {
    :where(:root) {
${indent(lightDark, 6)}
    }
  }

  /* Content over media (Astryx MediaTheme): pins the dark or light side of each pair. */
  :where([data-media-theme="dark"]) {
${indent(mediaBlock('dark'), 4)}
  }
  :where([data-media-theme="light"]) {
${indent(mediaBlock('light'), 4)}
  }

  /* Forced colours: system colours for the roles whose meaning maps one to one. */
  @media (forced-colors: active) {
    :where(:root, [data-theme], [data-media-theme]) {
${indent(forced, 6)}
    }
  }
}
`;
  const css = `${GENERATED_BANNER('tokens.css', 'Design tokens: Astryx semantic names, Tecton roles (--tecton-*), light and dark.')}
${LAYER_STATEMENT}

${body}`;
  return {css, body};
}

/** `palette.css`: the 1,820 opt-in primitives (component CSS may never reference them; lint). */
export function emitPaletteCss(palette: Palette): string {
  const lines = palette.entries.map(
    (entry) =>
      `${entry.name}: ${entry.value};${entry.alias === undefined ? '' : ` /* ${entry.alias} */`}`,
  );
  return `${GENERATED_BANNER('palette.css', `Opt-in raw palette: ${palette.entries.length} primitives from tecton.tokens.json. Component CSS never references these.`)}
${LAYER_STATEMENT}

@layer tecton.tokens {
  :where(:root) {
${indent(lines.join('\n'), 4)}
  }
}
`;
}
