/** Metadata outputs: `tokens.{js,d.ts,json}`, `fallbacks.json`, the committed name snapshot (A§5.4, §5.5). */
import type {Inputs, Mode, Token, TokenStatus} from './model.ts';
import {cssValue} from './resolve.ts';

export interface TokenMeta {
  name: string;
  category: string;
  /** Resolved CSS value in light mode (references followed). */
  light: string;
  dark: string;
  /** Palette paths (`foundational.color…`) or null for literals. Shadows list `a + b`. */
  lightPath: string | null;
  darkPath: string | null;
  source: string;
  status: TokenStatus;
  description: string;
  /** Present for provisional tokens (D-002): why the value is only proposed. */
  provisional?: string;
  /** Present for `retained-default` tokens (D-013): why the upstream value is kept. */
  retained?: string;
  /** Present for tokens settled as Tecton-derived by decision (D-013 Q-06). */
  derived?: string;
  /** Present when `bindings.overrides.json` changed the token (D-001). */
  override?: string;
}

function paletteOf(token: Token, mode: Mode): string | null {
  const value = token.value;
  if (value.kind === 'color') return (mode === 'light' ? value.lightPath : value.darkPath) ?? null;
  if (value.kind === 'shadow')
    return [...new Set(value.parts.map((part) => part[mode].path))].join(' + ');
  if (value.kind === 'ref') return null;
  return null;
}

export function tokenMeta(token: Token, byName: ReadonlyMap<string, Token>): TokenMeta {
  const meta: TokenMeta = {
    name: token.name,
    category: token.category,
    light: cssValue(token, 'light', byName, true),
    dark: cssValue(token, 'dark', byName, true),
    lightPath: paletteOf(token, 'light'),
    darkPath: paletteOf(token, 'dark'),
    source: token.source,
    status: token.status,
    description: token.description,
  };
  if (token.provisional !== undefined) meta.provisional = token.provisional;
  if (token.retained !== undefined) meta.retained = token.retained;
  if (token.derived !== undefined) meta.derived = token.derived;
  if (token.override) meta.override = token.override.reason;
  return meta;
}

/** `token name -> light value` for the Vite CSS plugin (A§5.5). Colour, size, font and shadow tokens alike. */
export function fallbacksJson(
  tokens: readonly Token[],
  byName: ReadonlyMap<string, Token>,
): string {
  const out: Record<string, string> = {};
  for (const token of tokens) out[token.name] = cssValue(token, 'light', byName, true);
  return `${JSON.stringify(out, null, 2)}\n`;
}

/** The committed API guard `snapshots/token-names.json` (A§3): sorted, tokens.css names only (no palette). */
export function snapshotJson(tokens: readonly Token[]): string {
  const names = tokens.map((token) => token.name).sort();
  return `${JSON.stringify(
    {
      $comment:
        'Generated by packages/tokens/scripts/generate.ts (pnpm generate). Names emitted by tokens.css: every public custom property. Never edit by hand; review any diff like an API change.',
      count: names.length,
      names,
    },
    null,
    2,
  )}\n`;
}

export interface TokensJsonInput {
  tokens: readonly Token[];
  byName: ReadonlyMap<string, Token>;
  inputs: Inputs;
  lockHashes: Record<string, string>;
  paletteCount: number;
  fonts: {xHeightRatio: {body: number; code: number}};
}

export function tokensJson(input: TokensJsonInput): string {
  const metas: Record<string, TokenMeta> = {};
  for (const token of input.tokens) metas[token.name] = tokenMeta(token, input.byName);
  const statusCounts: Record<string, number> = {};
  for (const token of input.tokens)
    statusCounts[token.status] = (statusCounts[token.status] ?? 0) + 1;
  const document = {
    version: 1,
    inputs: input.lockHashes,
    counts: {tokens: input.tokens.length, palette: input.paletteCount, byStatus: statusCounts},
    breakpoints: {
      status: 'retained-default',
      note: input.inputs.semanticMap.breakpoints.notes ?? '',
      values: input.inputs.semanticMap.breakpoints.values,
    },
    provisionalNonTokens: input.inputs.provisional.nonTokens,
    retainedNonTokens: input.inputs.provisional.retainedDefault.nonTokens,
    tectonDerivedNonTokens: input.inputs.provisional.tectonDerived.nonTokens,
    fonts: {
      sans: {
        family: 'Figtree Variable',
        fallback: 'Figtree Fallback',
        xHeightRatio: input.fonts.xHeightRatio.body,
      },
      mono: {
        family: 'IBM Plex Mono',
        fallback: 'IBM Plex Mono Fallback',
        xHeightRatio: input.fonts.xHeightRatio.code,
      },
    },
    tokens: metas,
  };
  return `${JSON.stringify(document, null, 2)}\n`;
}

/** `tokens.js`: the metadata as an ES module, plus `tokenVar()`. */
export function tokensJs(json: string): string {
  const data = JSON.parse(json) as {
    tokens: Record<string, TokenMeta>;
    breakpoints: unknown;
    provisionalNonTokens: unknown;
    retainedNonTokens: unknown;
    tectonDerivedNonTokens: unknown;
  };
  return `// GENERATED by packages/tokens/scripts/generate.ts. Do not edit.
// Design-token metadata for docs and tools. Runtime styling uses tokens.css, never this module.

export const tokens = Object.freeze(${JSON.stringify(data.tokens)});

/** Upstream breakpoints, retained on purpose (D-013). Custom properties cannot be used in media queries, so they are data only. */
export const breakpoints = Object.freeze(${JSON.stringify(data.breakpoints)});

/** Provisional items that have no custom property (D-002). */
export const provisionalNonTokens = Object.freeze(${JSON.stringify(data.provisionalNonTokens)});

/** Upstream values kept on purpose that have no custom property: breakpoints, z-index (D-013 Q-06). */
export const retainedNonTokens = Object.freeze(${JSON.stringify(data.retainedNonTokens)});

/**
 * Tecton-derived items that have no custom property (D-013 Q-06): letter-spacing (normal) and the
 * destructive button, whose binds name the --tecton-color-status-error-* roles it is painted from.
 */
export const tectonDerivedNonTokens = Object.freeze(${JSON.stringify(data.tectonDerivedNonTokens)});

/** \`var(--name)\` (with an optional fallback) for a known token name. */
export function tokenVar(name, fallback) {
  return fallback === undefined ? \`var(\${name})\` : \`var(\${name}, \${fallback})\`;
}
`;
}

export function tokensDts(tokens: readonly Token[]): string {
  const names = tokens.map((token) => `  | ${JSON.stringify(token.name)}`).join('\n');
  return `// GENERATED by packages/tokens/scripts/generate.ts. Do not edit.

export type TokenName =
${names};

export type TokenStatus =
  | 'tecton-export'
  | 'tecton-binding'
  | 'upstream-default'
  | 'retained-default'
  | 'provisional';

export interface TokenMeta {
  readonly name: TokenName;
  readonly category: string;
  /** Resolved CSS value in light mode (references followed). */
  readonly light: string;
  readonly dark: string;
  /** Palette paths (\`foundational.color...\`); null for literals and references. */
  readonly lightPath: string | null;
  readonly darkPath: string | null;
  readonly source: string;
  readonly status: TokenStatus;
  readonly description: string;
  /** Present for provisional tokens (D-002). */
  readonly provisional?: string;
  /** Present for retained-default tokens (D-013): why the upstream value is kept. */
  readonly retained?: string;
  /** Present for tokens settled as Tecton-derived by decision (D-013 Q-06). */
  readonly derived?: string;
  /** Present when bindings.overrides.json changed the token (D-001). */
  readonly override?: string;
}

export declare const tokens: Readonly<Record<TokenName, TokenMeta>>;
export declare const breakpoints: {
  readonly status: 'retained-default';
  readonly note: string;
  readonly values: Readonly<Record<'sm' | 'md' | 'lg' | 'xl' | '2xl', number>>;
};
export declare const provisionalNonTokens: ReadonlyArray<{readonly name: string; readonly reason: string}>;
export declare const retainedNonTokens: ReadonlyArray<{readonly name: string; readonly reason: string}>;
export declare const tectonDerivedNonTokens: ReadonlyArray<{
  readonly name: string;
  readonly reason: string;
  readonly value?: string;
  readonly binds?: Readonly<Record<string, TokenName>>;
}>;
export declare function tokenVar(name: TokenName, fallback?: string): string;
`;
}
