/**
 * Static shared stylesheets of the components package (A§3, A§6.7, A§6.8):
 *
 *  - `cloak.css`      optional FOUC cloak: `:not(:defined)` elements are transparent, with a fail-open
 *                     timeout (`--tct-cloak-timeout`, default 2s) so a missing script never hides the
 *                     page; per-tag `display` / `min-block-size` reserve space from `@cloakDisplay` /
 *                     `@cloakMinBlockSize`. [mwg:custom-elements]
 *  - `light-dom.css`  every `<folder>/*.light.css` concatenated (light-DOM families, A§6.7)
 *  - `tecton.css`     tokens' `tecton.css` (tokens + fonts) + light-dom.css + cloak.css: the one-link bundle
 */
import {readFileSync} from 'node:fs';
import {basename, join} from 'node:path';
import {cemElements, type CemPackage} from '../lib/cem.ts';
import {listDirs, walkFiles} from '../lib/fs.ts';

const LAYER_ORDER = '@layer tecton.reset, tecton.tokens, tecton.light-dom;';
export const BANNER =
  '/* GENERATED by tools/css/generate-shared.ts. Do not edit; do not commit. */\n';

const CSS_LENGTH_OR_KEYWORD = /^[\w\s.%()+*/,-]+$/;

function assertSafe(tag: string, property: string, value: string): string {
  // The values come from source JSDoc; keep them from breaking out of a declaration.
  if (!CSS_LENGTH_OR_KEYWORD.test(value)) {
    throw new Error(`${tag}: ${property} value "${value}" is not a plain CSS keyword or length`);
  }
  return value;
}

export function cloakCss(cem: CemPackage): string {
  const elements = cemElements(cem);
  const header =
    `${BANNER}/*!\n * @tecton-wc/components: cloak.css\n` +
    ` * Optional. Hides not-yet-defined tct-* elements to avoid a flash of unstyled content and\n` +
    ` * reveals them after --tct-cloak-timeout (default 2s) even if their script never runs.\n */\n`;
  if (elements.length === 0) return `${header}${LAYER_ORDER}\n`;

  const selector = elements.map((element) => element.tagName).join(',\n  ');
  const rules = elements.flatMap(({tagName, declaration}) => {
    const display = declaration['x-tct']?.cloakDisplay;
    const minBlockSize = declaration['x-tct']?.cloakMinBlockSize;
    const lines = [
      display ? `    display: ${assertSafe(tagName, '@cloakDisplay', display)};` : undefined,
      minBlockSize
        ? `    min-block-size: ${assertSafe(tagName, '@cloakMinBlockSize', minBlockSize)};`
        : undefined,
    ].filter((line): line is string => line !== undefined);
    return lines.length > 0 ? [`  ${tagName}:not(:defined) {\n${lines.join('\n')}\n  }`] : [];
  });

  return (
    `${header}${LAYER_ORDER}\n\n@layer tecton.reset {\n` +
    `  :is(\n  ${selector}\n  ):not(:defined) {\n` +
    `    opacity: 0;\n` +
    `    animation: tct-cloak-reveal 0.2s var(--tct-cloak-timeout, 2s) forwards;\n  }\n\n` +
    (rules.length > 0 ? `${rules.join('\n\n')}\n\n` : '') +
    `  @keyframes tct-cloak-reveal {\n    to {\n      opacity: 1;\n    }\n  }\n\n` +
    `  @media (prefers-reduced-motion: reduce) {\n    :is(\n    ${selector}\n    ):not(:defined) {\n      animation-duration: 0.01ms;\n    }\n  }\n}\n`
  );
}

/** `<folder>/*.light.css` files of every component family, sorted. */
export function lightDomSources(componentsSrc: string): string[] {
  const files: string[] = [];
  for (const folder of listDirs(componentsSrc)) {
    if (folder === 'generated' || folder === 'styles') continue;
    const dir = join(componentsSrc, folder);
    for (const file of walkFiles(dir, {skipDirs: ['examples', '__snapshots__']})) {
      if (file.endsWith('.light.css') && !file.slice(dir.length + 1).includes('/'))
        files.push(file);
    }
  }
  return files.sort();
}

export function lightDomCss(componentsSrc: string): string {
  const files = lightDomSources(componentsSrc);
  const header =
    `${BANNER}/*!\n * @tecton-wc/components: light-dom.css\n` +
    ` * Styles of light-DOM families, in @layer tecton.light-dom. Load once per document.\n */\n${LAYER_ORDER}\n`;
  if (files.length === 0) return header;
  const parts = files.map((file) => {
    const folder = basename(join(file, '..'));
    return `\n/* ${folder}/${basename(file)} */\n${readFileSync(file, 'utf8').trimEnd()}\n`;
  });
  return `${header}${parts.join('')}`;
}

/** tokens' one-link bundle plus this package's light-dom.css and cloak.css. */
export function tectonCss(tokensTecton: string, lightDom: string, cloak: string): string {
  const strip = (css: string) => css.replace(/^\/\* GENERATED[^\n]*\n/, '');
  return (
    `${tokensTecton.trimEnd()}\n\n/* ---- light-dom.css ---- */\n${strip(lightDom)}\n` +
    `/* ---- cloak.css ---- */\n${strip(cloak)}`
  );
}
