/**
 * Locating and reading the agent registry. The CLI reads the same file the docs site serves; nothing here
 * derives anything (D-011).
 *
 * Order: the `--registry <file>` option, `$TCT_AGENT_REGISTRY`, the nearest `@tecton-wc/components`
 * installed for the project (walking up from the working directory), the workspace copy
 * (`packages/components/agent-registry.json`, generated by `pnpm generate`), then the copy this package
 * depends on. A project's own install wins, so the answers match the version the project actually uses.
 */
import {existsSync, readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {dirname, join, resolve} from 'node:path';
import {ERROR_CODES, CliError} from '../errors.ts';
import {SUPPORTED_SCHEMA_VERSIONS, type AgentRegistry} from './types.ts';

export type RegistrySource = 'option' | 'env' | 'project' | 'workspace' | 'bundled';

export interface LoadedRegistry {
  registry: AgentRegistry;
  path: string;
  source: RegistrySource;
}

export interface LoadOptions {
  cwd: string;
  /** The `--registry` option. */
  path?: string;
  env?: Record<string, string | undefined>;
}

/** Package specifier of the registry export of the components package. */
export const REGISTRY_SPECIFIER = '@tecton-wc/components/agent-registry.json';

export function locateRegistry(
  options: LoadOptions,
): {path: string; source: RegistrySource} | null {
  const cwd = resolve(options.cwd);
  if (options.path) {
    return {path: resolve(cwd, options.path), source: 'option'};
  }
  const fromEnv = options.env?.TCT_AGENT_REGISTRY;
  if (fromEnv) return {path: resolve(cwd, fromEnv), source: 'env'};

  for (let dir = cwd; ; dir = dirname(dir)) {
    const installed = join(dir, 'node_modules/@tecton-wc/components/agent-registry.json');
    if (existsSync(installed)) return {path: installed, source: 'project'};
    const workspace = join(dir, 'packages/components/agent-registry.json');
    if (existsSync(workspace)) return {path: workspace, source: 'workspace'};
    if (dirname(dir) === dir) break;
  }
  try {
    const bundled = createRequire(import.meta.url).resolve(REGISTRY_SPECIFIER);
    if (existsSync(bundled)) return {path: bundled, source: 'bundled'};
  } catch {
    // Not resolvable from here either.
  }
  return null;
}

/** Validates a parsed registry. Throws `ERR_REGISTRY_INCOMPATIBLE` when it is not one this CLI can read. */
export function assertRegistry(value: unknown, where: string): AgentRegistry {
  const registry = value as Partial<AgentRegistry> | null;
  if (
    !registry ||
    typeof registry !== 'object' ||
    !Array.isArray(registry.components) ||
    !Array.isArray(registry.topics) ||
    typeof registry.schemaVersion !== 'number'
  ) {
    throw new CliError(
      `${where} is not an agent registry.`,
      ERROR_CODES.ERR_REGISTRY_INCOMPATIBLE,
      [{name: 'pnpm generate', reason: 'regenerates the registry in the workspace'}],
    );
  }
  if (!SUPPORTED_SCHEMA_VERSIONS.includes(registry.schemaVersion)) {
    throw new CliError(
      `${where} has registry schema version ${registry.schemaVersion}; this CLI reads ${SUPPORTED_SCHEMA_VERSIONS.join(', ')}.`,
      ERROR_CODES.ERR_REGISTRY_INCOMPATIBLE,
      [{name: 'align @tecton-wc/cli and @tecton-wc/components versions'}],
    );
  }
  // Older generators (schema 2 drafts) may lack optional collections: tolerate them.
  return {
    tokens: [],
    tokenCounts: null,
    controllers: [],
    categories: [],
    ...registry,
  } as AgentRegistry;
}

export function loadRegistry(options: LoadOptions): LoadedRegistry {
  const located = locateRegistry(options);
  if (!located) {
    throw new CliError(
      'Could not find the agent registry (@tecton-wc/components/agent-registry.json).',
      ERROR_CODES.ERR_REGISTRY_NOT_FOUND,
      [
        {
          name: 'pnpm install @tecton-wc/components',
          reason: 'installs the package that ships the registry',
        },
        {name: '--registry <file>', reason: 'or point at a registry file explicitly'},
        {name: 'TCT_AGENT_REGISTRY=<file>', reason: 'or set it in the environment'},
      ],
    );
  }
  if (!existsSync(located.path)) {
    throw new CliError(`Registry file not found: ${located.path}`, ERROR_CODES.ERR_FILE_NOT_FOUND);
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(located.path, 'utf8'));
  } catch (error) {
    throw new CliError(
      `Cannot read ${located.path}: ${(error as Error).message}`,
      ERROR_CODES.ERR_REGISTRY_INCOMPATIBLE,
    );
  }
  return {registry: assertRegistry(parsed, located.path), ...located};
}
