/**
 * Barrel generators (A§3): everything that aggregates across components is derived from globs, so a
 * new component folder never edits a shared file. Outputs are gitignored (`**\/generated/`).
 *
 *  - `packages/components/src/generated/index.ts`         class + type barrel, no registration
 *  - `packages/components/src/generated/define-all.ts`    registers every family
 *  - `packages/components/src/generated/autoloader-map.ts` tag -> folder map for the autoloader
 *  - `packages/core/src/generated/index.ts`               core barrel
 *
 * Pure functions: they return file contents; `tools/generate.ts` writes them.
 */
import {readFileSync} from 'node:fs';
import {basename, join, relative} from 'node:path';
import {isFile, listDirs, walkFiles} from '../lib/fs.ts';
import {scanExports, scanTagName, type ScannedExports} from '../lib/exports.ts';

export const GENERATED_BANNER =
  '// GENERATED by tools/generate.ts. Do not edit; do not commit (ARCHITECTURE §3).\n';

export interface GeneratedFile {
  /** Absolute output path. */
  path: string;
  content: string;
}

/** Folder names under `src/` that are not component families. */
const NON_FAMILY_DIRS = new Set(['generated', 'styles', '__snapshots__']);

const isTestFile = (file: string) => /\.(?:node\.)?test\.ts$/.test(file);

/** Component family folders: direct children of `src/` that contain a `define.ts`. */
export function componentFolders(componentsSrc: string): string[] {
  return listDirs(componentsSrc).filter(
    (name) => !NON_FAMILY_DIRS.has(name) && isFile(join(componentsSrc, name, 'define.ts')),
  );
}

function folderFiles(folderPath: string): string[] {
  return walkFiles(folderPath, {skipDirs: ['__snapshots__', 'examples']}).filter(
    (file) => relative(folderPath, file).split(/[\\/]/).length === 1 && file.endsWith('.ts'),
  );
}

/** Files of a family that the class barrel re-exports: classes, types and imperative APIs. */
function barrelSources(folderPath: string): string[] {
  return folderFiles(folderPath).filter((file) => {
    const name = basename(file);
    if (isTestFile(file) || name.endsWith('.d.ts') || name === 'define.ts') return false;
    return /^tct-.+\.ts$/.test(name) || /\.(?:types|api)\.ts$/.test(name);
  });
}

class DuplicateTracker {
  #seen = new Map<string, string>();
  readonly #what: string;
  constructor(what: string) {
    this.#what = what;
  }
  add(name: string, origin: string): void {
    const previous = this.#seen.get(name);
    if (previous !== undefined) {
      throw new Error(
        `Duplicate ${this.#what} "${name}" exported by ${previous} and ${origin}. ` +
          `Rename one of them (named re-exports only; A§3).`,
      );
    }
    this.#seen.set(name, origin);
  }
}

function exportLine(exports: ScannedExports, specifier: string): string[] {
  const lines: string[] = [];
  if (exports.values.length > 0)
    lines.push(`export {${exports.values.join(', ')}} from '${specifier}';`);
  if (exports.types.length > 0) {
    lines.push(`export type {${exports.types.join(', ')}} from '${specifier}';`);
  }
  return lines;
}

function scanFile(file: string): ScannedExports {
  const exports = scanExports(readFileSync(file, 'utf8'));
  if (exports.hasExportStar) {
    throw new Error(`${file}: \`export *\` cannot be re-exported by name; use named exports.`);
  }
  return exports;
}

export function generateComponentsBarrels(componentsSrc: string): GeneratedFile[] {
  const folders = componentFolders(componentsSrc);
  const names = new DuplicateTracker('export name');
  const defineNames = new DuplicateTracker('define export name');
  const tags = new DuplicateTracker('tag name');

  const indexLines: string[] = [];
  const defineLines: string[] = [];
  const mapEntries: [string, string][] = [];

  for (const folder of folders) {
    const folderPath = join(componentsSrc, folder);

    for (const file of barrelSources(folderPath)) {
      const exports = scanFile(file);
      for (const name of [...exports.values, ...exports.types])
        names.add(name, `${folder}/${basename(file)}`);
      indexLines.push(
        ...exportLine(exports, `../${folder}/${basename(file).replace(/\.ts$/, '.js')}`),
      );

      const tag = scanTagName(readFileSync(file, 'utf8'));
      if (tag !== undefined) {
        tags.add(tag, `${folder}/${basename(file)}`);
        mapEntries.push([tag, folder]);
      }
    }

    // define-all: registers the family and re-exports what its define.ts re-exports (named only).
    const define = scanFile(join(folderPath, 'define.ts'));
    for (const name of [...define.values, ...define.types])
      defineNames.add(name, `${folder}/define.ts`);
    defineLines.push(
      `import '../${folder}/define.js';`,
      ...exportLine(define, `../${folder}/define.js`),
    );
  }

  const outDir = join(componentsSrc, 'generated');
  const emptyNote = folders.length === 0 ? '// No component families yet.\n' : '';
  const sortedMap = mapEntries.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));

  return [
    {
      path: join(outDir, 'index.ts'),
      content: `${GENERATED_BANNER}${emptyNote}${indexLines.join('\n')}${indexLines.length ? '\n' : ''}export {};\n`,
    },
    {
      path: join(outDir, 'define-all.ts'),
      content: `${GENERATED_BANNER}${emptyNote}${defineLines.join('\n')}${defineLines.length ? '\n' : ''}export {};\n`,
    },
    {
      path: join(outDir, 'autoloader-map.ts'),
      content:
        `${GENERATED_BANNER}// tag name -> component family folder (derived from \`static tagName\`).\n` +
        `export const autoloaderMap: Readonly<Record<string, string>> = {\n` +
        sortedMap.map(([tag, folder]) => `  '${tag}': '${folder}',`).join('\n') +
        `${sortedMap.length ? '\n' : ''}};\n`,
    },
  ];
}

/** Core sources the barrel skips: tests, declarations, generated output, `internal/` directories. */
function coreBarrelSources(coreSrc: string): string[] {
  return walkFiles(coreSrc, {skipDirs: ['generated', 'internal', '__snapshots__']}).filter(
    (file) => {
      if (!file.endsWith('.ts') || file.endsWith('.d.ts') || isTestFile(file)) return false;
      return !relative(coreSrc, file)
        .split(/[\\/]/)
        .some((part) => part.startsWith('_'));
    },
  );
}

export function generateCoreBarrel(coreSrc: string): GeneratedFile[] {
  const names = new DuplicateTracker('export name');
  const lines: string[] = [];
  for (const file of coreBarrelSources(coreSrc)) {
    const exports = scanFile(file);
    const shown = relative(coreSrc, file).split('\\').join('/');
    for (const name of [...exports.values, ...exports.types]) names.add(name, shown);
    lines.push(...exportLine(exports, `../${shown.replace(/\.ts$/, '.js')}`));
  }
  return [
    {
      path: join(coreSrc, 'generated', 'index.ts'),
      content: `${GENERATED_BANNER}${lines.join('\n')}${lines.length ? '\n' : ''}export {};\n`,
    },
  ];
}
