/**
 * `pnpm build` (A§2.3, A§2.5, A§14): builds every package into its `dist/`.
 *
 *   tokens      generated by `pnpm generate` (CSS, metadata, fonts); build only prunes stale output
 *   locales     generated catalogs; tsc adds types.d.ts
 *   icons       Vite library build (preserveModules) + declarations
 *   core        Vite library build (preserveModules) + declarations
 *   components  Vite library build + declarations + the CDN bundle (code split, no externals) in dist/cdn
 *   testing     not built: dev only, its exports point at source
 *
 * Library builds keep every module as its own file (`preserveModules`) and leave every bare import
 * external. Declarations come from `tsc -p <package>/tsconfig.build.json --emitDeclarationOnly`, whose
 * config excludes tests, fixtures and generator inputs, so no test `.d.ts` or `pipeline/` reaches
 * `dist`. Afterwards: every package's `exports` are checked against the output, and every built module is
 * imported in Node without a DOM (A§14), and the CDN bundle is loaded in Chromium and must define every tag.
 */
import {existsSync, readdirSync, rmSync} from 'node:fs';
import {join, relative} from 'node:path';
import {build} from 'vite';
import {libraryConfig, entryRecord, sourceModules} from './build/vite.ts';
import {main as cdnSmoke} from './build/cdn-smoke.ts';
import {main as serverImport} from './build/server-import.ts';
import {readPackage, verifyExports, workspaceResolveRoot} from './build/verify-exports.ts';
import {componentFolderNames} from './lib/docs-model.ts';
import {walkFiles} from './lib/fs.ts';
import {ROOT, rel} from './lib/paths.ts';
import {run} from './lib/run.ts';

const TSC = join(ROOT, 'node_modules/.bin/tsc');
const pkgDir = (name: string) => join(ROOT, 'packages', name);

function step(message: string): void {
  console.log(`  build ${message}`);
}

function tsc(name: string): void {
  const project = join(pkgDir(name), 'tsconfig.build.json');
  const result = run(TSC, ['-p', project, '--emitDeclarationOnly']);
  if (result.status !== 0) throw new Error(`tsc failed for @tecton-astryx/${name}`);
}

/** Removes everything in `dist` except the generated files named in `keep` (top-level names). */
function clean(name: string, keep: readonly string[] = []): void {
  const dist = join(pkgDir(name), 'dist');
  if (!existsSync(dist)) return;
  for (const entry of readdirSync(dist)) {
    if (!keep.includes(entry)) rmSync(join(dist, entry), {recursive: true, force: true});
  }
}

/** Test declarations and generator internals that older type-check runs left behind. */
function pruneStale(name: string): void {
  const dist = join(pkgDir(name), 'dist');
  for (const stale of ['pipeline', 'inputs', '.tsbuildinfo', 'env.d.ts', 'env.d.ts.map']) {
    rmSync(join(dist, stale), {recursive: true, force: true});
  }
  for (const file of walkFiles(dist, {skipDirs: ['fonts']})) {
    if (/\.(?:node\.)?test\.d\.ts(?:\.map)?$/.test(file)) rmSync(file);
  }
}

async function library(name: string, options: {skip?: readonly string[]} = {}): Promise<void> {
  const src = join(pkgDir(name), 'src');
  const files = sourceModules(src, options.skip ?? []);
  step(`@tecton-astryx/${name}: ${files.length} module(s)`);
  await build(
    libraryConfig({
      entry: entryRecord(src, files),
      outDir: join(pkgDir(name), 'dist'),
      srcRoot: src,
      preserveModules: true,
    }),
  );
  tsc(name);
}

/** The CDN bundle (A§2.5): one entry per family plus the autoloader and define-all, code split, no externals. */
async function cdn(): Promise<void> {
  const src = join(pkgDir('components'), 'src');
  const entry: Record<string, string> = {
    autoloader: join(src, 'autoloader.ts'),
    define: join(src, 'generated/define-all.ts'),
  };
  for (const file of walkFiles(src, {
    skipDirs: ['generated', 'styles', '__snapshots__', 'examples'],
  })) {
    const parts = relative(src, file).split(/[\\/]/);
    if (parts.length === 2 && parts[1] === 'define.ts') entry[parts[0]!] = file;
  }
  const outDir = join(pkgDir('components'), 'dist/cdn');
  rmSync(outDir, {recursive: true, force: true});
  step(
    `CDN bundle: ${Object.keys(entry).length} entr${Object.keys(entry).length === 1 ? 'y' : 'ies'} -> ${rel(outDir)}`,
  );
  await build(libraryConfig({entry, outDir, srcRoot: src, bundle: true, chunkDir: 'chunks'}));
}

async function main(): Promise<number> {
  if (process.env.TCT_GENERATED !== '1') {
    const generated = run('node', ['tools/generate.ts']);
    if (generated.status !== 0) return generated.status;
  }
  console.log('build');

  try {
    pruneStale('tokens');
    pruneStale('locales');
    step('@tecton-astryx/tokens: generated (pruned stale output)');
    step('@tecton-astryx/locales: generated catalogs + types');
    tsc('locales');

    clean('icons');
    await library('icons', {skip: ['glyphs']});

    clean('core');
    await library('core');

    clean('components', ['tecton.css', 'light-dom.css', 'cloak.css', 'fonts']);
    await library('components');
    await cdn();
  } catch (error) {
    console.error(`build: ${(error as Error).message}`);
    return 1;
  }

  // Every package's exports must resolve for the built output.
  const problems: string[] = [];
  const families = componentFolderNames(join(pkgDir('components'), 'src')).length;
  let checked = 0;
  for (const name of ['tokens', 'locales', 'icons', 'core', 'components']) {
    const pkg = readPackage(pkgDir(name));
    const report = verifyExports(pkg, {
      resolveFrom: workspaceResolveRoot(pkg.name),
      // `"./*"` maps `<folder>` to `<folder>/define`: nothing to match before the first component folder.
      allowEmpty: name === 'components' && families === 0 ? ['./*'] : [],
    });
    problems.push(...report.problems);
    checked += report.checked;
  }
  if (problems.length > 0) {
    for (const problem of problems) console.error(`build: exports: ${problem}`);
    console.error(`\nbuild FAILED: ${problems.length} exports problem(s).`);
    return 1;
  }
  console.log(`  build exports: ${checked} export target(s) resolve for the built output`);

  const status = await serverImport();
  return status === 0 ? cdnSmoke() : status;
}

process.exit(await main());
