/**
 * `pnpm parity`: writes reports/parity.{json,md} from the upstream manifest (184 core + 67 extension
 * entries) and every parity.json (A§15.5). The M1 report covers status, API mapping coverage and
 * test/docs presence; M6 extends it (theming, keyboard, docs sections) and feeds the docs site.
 */
import {existsSync, mkdirSync, writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {
  checkParity,
  discoverParityFiles,
  expectedApiNames,
  loadManifest,
  loadSchema,
  type ParityEntry,
} from './lib/parity.ts';
import {PATHS, ROOT, rel} from './lib/paths.ts';

const manifest = loadManifest(PATHS.manifest);
const schema = loadSchema(PATHS.paritySchema);
const docsSchema = loadSchema(PATHS.docsFrontmatterSchema);
const {problems, parity} = checkParity({
  manifest,
  schema,
  docsSchema,
  files: discoverParityFiles(ROOT),
});

const recorded = new Map<string, {folder: string; entry: ParityEntry}>();
for (const {data} of parity) {
  for (const [id, entry] of Object.entries(data.entries))
    recorded.set(id, {folder: data.folder, entry});
}

const rows = manifest.entries.map((upstream) => {
  const found = recorded.get(upstream.id);
  const expected = expectedApiNames(upstream);
  const mapped = new Set(found?.entry.api.map((row) => row.upstream) ?? []);
  const waived = found?.entry.api.filter((row) => row.as === 'waived').length ?? 0;
  return {
    id: upstream.id,
    name: upstream.name,
    package: upstream.package,
    tier: upstream.package === '@astryxdesign/core' ? 'core' : 'extension',
    folder: found?.folder ?? null,
    tag: found?.entry.tag ?? null,
    status: found?.entry.status ?? 'not-started',
    apiExpected: expected.length,
    apiMapped: expected.filter((name) => mapped.has(name)).length,
    apiWaived: waived,
    testCategories: Object.entries(found?.entry.tests ?? {})
      .filter(([, on]) => on)
      .map(([name]) => name),
  };
});

const statuses = ['not-started', 'in-progress', 'implemented', 'verified'] as const;
type TierSummary = {total: number} & Record<(typeof statuses)[number], number>;

function summarize(tier: 'core' | 'extension'): TierSummary {
  const tierRows = rows.filter((row) => row.tier === tier);
  const counts = Object.fromEntries(
    statuses.map((status) => [status, tierRows.filter((row) => row.status === status).length]),
  ) as Record<(typeof statuses)[number], number>;
  return {total: tierRows.length, ...counts};
}
const summary: Record<'core' | 'extension', TierSummary> = {
  core: summarize('core'),
  extension: summarize('extension'),
};

const report = {
  generatedFrom: {
    manifestCommit: manifest.baseline.commit,
    parityFiles: parity.map((p) => rel(p.file)),
  },
  summary,
  problems,
  entries: rows,
};

const markdown = [
  '# Parity report',
  '',
  `Upstream Astryx at \`${manifest.baseline.commit.slice(0, 7)}\`. Generated by \`pnpm parity\`; do not edit.`,
  '',
  '| Tier | Total | Not started | In progress | Implemented | Verified |',
  '| --- | ---: | ---: | ---: | ---: | ---: |',
  ...Object.entries(summary).map(
    ([tier, s]) =>
      `| ${tier} | ${s.total} | ${s['not-started']} | ${s['in-progress']} | ${s.implemented} | ${s.verified} |`,
  ),
  '',
  ...(problems.length > 0
    ? ['## Problems', '', ...problems.map((p) => `- \`${p.file}\`: ${p.message}`), '']
    : []),
  '## Entries',
  '',
  '| Entry | Folder | Tag | Status | API mapped | Waived |',
  '| --- | --- | --- | --- | ---: | ---: |',
  ...rows.map(
    (row) =>
      `| ${row.id} | ${row.folder ?? ''} | ${row.tag ?? ''} | ${row.status} | ${row.apiMapped}/${row.apiExpected} | ${row.apiWaived} |`,
  ),
  '',
].join('\n');

if (!existsSync(PATHS.reports)) mkdirSync(PATHS.reports, {recursive: true});
writeFileSync(join(PATHS.reports, 'parity.json'), `${JSON.stringify(report, null, 2)}\n`);
writeFileSync(join(PATHS.reports, 'parity.md'), markdown);
console.log(
  `parity: wrote reports/parity.{json,md} (${rows.length} entries; ` +
    `${rows.filter((row) => row.status !== 'not-started').length} started).`,
);
